# Generated by Django 4.2.1 on 2023-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0018_alter_user_address_alter_user_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The email must be unique!'}, max_length=50, unique=True, verbose_name='Company email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='0_DynamicImages/profile-picturs', verbose_name='Company image'),
        ),
    ]
