# Generated by Django 4.2.1 on 2023-05-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0019_remove_user_address_remove_user_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Company Name'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
