# Generated by Django 4.2.1 on 2023-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0020_alter_user_options_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Employee', 'Employee')], max_length=30, null=True),
        ),
    ]
