# Generated by Django 4.2.1 on 2023-05-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0022_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserType',
            new_name='user_type',
        ),
    ]
