# Generated by Django 4.2.1 on 2023-05-18 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0023_alter_user_options_rename_usertype_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employe',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
