# Generated by Django 4.2.1 on 2023-05-18 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
