# Generated by Django 4.2.1 on 2023-05-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_employee_employee_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
