# Generated by Django 4.2.1 on 2023-05-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeV',
        ),
    ]
