# Generated by Django 4.2.1 on 2023-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAsset', '0003_companyasset_employee_list'),
        ('employee', '0005_rename_employee_employeev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeev',
            name='asset',
        ),
        migrations.AddField(
            model_name='employeev',
            name='asset',
            field=models.ManyToManyField(blank=True, null=True, to='companyAsset.companyasset'),
        ),
    ]
