# Generated by Django 4.2.1 on 2023-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employeev_asset_employeev_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeev',
            name='back_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeev',
            name='taking_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
