# Generated by Django 4.2.1 on 2023-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeev_back_time_employeev_taking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeev',
            name='asset',
        ),
        migrations.AddField(
            model_name='employeev',
            name='asset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
