# Generated by Django 4.2.1 on 2023-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employeev_asset_employeev_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeev',
            name='back_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeev',
            name='taking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
