# Generated by Django 4.2.1 on 2023-05-18 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyAsset', '0002_companyasset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyasset',
            name='employee_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
